# Generated by Django 2.2.13 on 2024-05-05 05:48

from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('river', '0002_auto_20240503_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True, verbose_name='Employee Number')),
                ('firstname', models.CharField(max_length=122, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=122, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('Aadhar_number', models.BigIntegerField(verbose_name='Aadhar Number')),
                ('pan_number', models.CharField(max_length=10, verbose_name='PAN Number')),
                ('status', river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State')),
            ],
        ),
    ]
